<a href="https://colab.research.google.com/github/SarahSchilling618/project-4/blob/julius/Dementia_Get_Dummies_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd

# Replace 'file_path.csv' with the path to your CSV file
file_path = "C:\\Users\\juliu\\Downloads\\dementia_get_dummies.csv"

# Read the CSV file into a DataFrame
df = pd.read_csv(file_path)

# Display the DataFrame
pd.set_option('display.max_columns', None)
print(df)


      Unnamed: 0  Diabetic  AlcoholLevel  HeartRate  BloodOxygenLevel  \
0              0         1      0.084974         98         96.230743   
1              1         0      0.016973         78         93.032122   
2              2         0      0.009000         89         93.566504   
3              3         0      0.086437         60         93.906510   
4              4         1      0.150747         67         97.508994   
...          ...       ...           ...        ...               ...   
1995        1995         1      0.125142         64         94.218010   
1996        1996         1      0.172027         75         90.475116   
1997        1997         1      0.100825         93         95.315495   
1998        1998         1      0.017496         75         99.859658   
1999        1999         0      0.030531         76         96.493361   

      BodyTemperature     Weight  MRI_Delay  Dosage_in_mg  Age  \
0           36.224852  57.563978  36.421028           NaN

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import mean_squared_error, accuracy_score

In [14]:
# Prepare the data for linear regression

X_linear = df.drop(columns=["Dementia"])
y_linear = df["Dementia"]

# Split the data into training and testing sets for linear regression
X_train_linear, X_test_linear, y_train_linear, y_test_linear = train_test_split(X_linear, y_linear, test_size=0.2, random_state=42)

# Train the linear regression model
linear_model = LinearRegression()
linear_model.fit(X_train_linear, y_train_linear)

# Make predictions on the test set for linear regression
y_pred_linear = linear_model.predict(X_test_linear)

# Evaluate the performance of the linear regression model
mse_linear = mean_squared_error(y_test_linear, y_pred_linear)
print("Mean Squared Error (MSE) for Linear Regression:", mse_linear)



Mean Squared Error (MSE) for Linear Regression: 0.0


In [20]:
X = df["Dementia"].values.reshape(-1, 1)

X[:5]

array([[1],
       [1],
       [1],
       [1],
       [1]], dtype=int64)

In [22]:
X.shape

(970, 1)

In [23]:
y = df["Diabetic"]

In [24]:
model = LinearRegression()

In [25]:
model.fit(X, y)

LinearRegression()

In [26]:
print(f"Model's slope: {model.coef_}")

Model's slope: [0.]


In [27]:
print(f"Model's y-intercept: {model.intercept_}")

Model's y-intercept: 0.5360824742268041


In [28]:
print(f"Model's formula: y = {model.intercept_} + {model.coef_[0]}X")

Model's formula: y = 0.5360824742268041 + 0.0X


In [29]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [30]:
X = df.drop(columns=['Dementia'])  # Features
y = df['Dementia']  # Target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 5: Train Model
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Step 6: Evaluate Model
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 1.0
Classification Report:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00       194

    accuracy                           1.00       194
   macro avg       1.00      1.00      1.00       194
weighted avg       1.00      1.00      1.00       194

Confusion Matrix:
[[194]]


In [38]:
X = df.drop(columns=['APOE_4_Positive', "APOE_4_Negative"])  # Features
y = df['APOE_4_Positive']  # Target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 5: Train Model
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Step 6: Evaluate Model
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9484536082474226
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.91      0.95       109
           1       0.89      1.00      0.94        85

    accuracy                           0.95       194
   macro avg       0.95      0.95      0.95       194
weighted avg       0.95      0.95      0.95       194

Confusion Matrix:
[[99 10]
 [ 0 85]]


In [33]:
X = df.drop(columns=['APOE_4_Positive', "APOE_4_Negative"])  # Features
y = df['APOE_4_Negative']  # Target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 5: Train Model
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Step 6: Evaluate Model
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9484536082474226
Classification Report:
              precision    recall  f1-score   support

           0       0.95      1.00      0.97       184
           1       0.00      0.00      0.00        10

    accuracy                           0.95       194
   macro avg       0.47      0.50      0.49       194
weighted avg       0.90      0.95      0.92       194

Confusion Matrix:
[[184   0]
 [ 10   0]]


C:\Users\juliu\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\juliu\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\juliu\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [34]:
X = df.drop(columns=['Dementia','APOE_4_Positive', "APOE_4_Negative"])  # Features
y = df['APOE_4_Positive']  # Target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 5: Train Model
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Step 6: Evaluate Model
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9484536082474226
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.91      0.95       109
           1       0.89      1.00      0.94        85

    accuracy                           0.95       194
   macro avg       0.95      0.95      0.95       194
weighted avg       0.95      0.95      0.95       194

Confusion Matrix:
[[99 10]
 [ 0 85]]
